package database

import org.jetbrains.exposed.sql.Table
import org.jetbrains.exposed.sql.javatime.timestamp
import java.time.Instant

object Characters : Table() {
    val id = integer("id").autoIncrement().uniqueIndex()
    val accountId = integer("accountId").references(Accounts.id)
    val world = integer("world").default(0)
    val name = varchar("name", 13).default("")
    val level = integer("level").default(1)
    val exp = integer("exp").default(0)
    val gachaExp = integer("gachaExp").default(0)
    val str = integer("str").default(12)
    val dex = integer("dex").default(5)
    val int = integer("int").default(4)
    val luk = integer("luk").default(4)
    val hp = integer("hp").default(50)
    val mp = integer("mp").default(5)
    val maxHp = integer("maxHp").default(50)
    val maxMp = integer("maxMp").default(5)
    val meso = integer("meso").default(0)
    val hpMpUsed = integer("hpMpUsed").default(0)
    val job = integer("job").default(0)
    val skinColor = integer("skinColor").default(0)
    val gender = integer("gender").default(0)
    val fame = integer("fame").default(0)
    val hair = integer("hair").default(0)
    val face = integer("face").default(0)
    val ap = integer("ap").default(0)
    val sp = integer("sp").default(0)
    val map = integer("map").default(0)
    val spawnPoint = integer("spawnPoint").default(0)
    val gm = byte("gm").default(0)
    val party = integer("party").default(0)
    val buddyCapacity = integer("buddyCapacity").default(25)
    val createDate = timestamp("createDate").clientDefault { Instant.now() }
    val rank = integer("rank").default(1)
    val rankMove = integer("rankMove").default(0)
    val jobRank = integer("jobRank").default(1)
    val jobRankMove = integer("jobRsetupslotsankMove").default(0)
    val guildId = integer("guildId").default(0)
    val guildRank = integer("guildRank").default(5)
    val messengerId = integer("messengerId").default(0)
    val messengerPosition = integer("messengerPosition").default(4)
    val mountLevel = integer("mountLevel").default(1)
    val mountExp = integer("mountExp").default(0)
    val mountTiredness = integer("mountTiredness").default(0)
    val omokWins = integer("omokWins").default(0)
    val omokLossess = integer("omokLosses").default(0)
    val omokTies = integer("omokTies").default(0)
    val matchCardWins = integer("matchCardWins").default(0)
    val matchCardLossess = integer("matchCardLossess").default(0)
    val matchCardTies = integer("matchCardTies").default(0)
    val merchantMesos = integer("merchantMesos").default(0)
    val hasMerchant = bool("hasMerchant").default(false)
    val equipSlots = integer("equipSlots").default(24)
    val useSlots = integer("useSlots").default(24)
    val setupSlots = integer("setupSlots").default(24)
    val etcSlots = integer("etcSlots").default(24)
    val monsterBookCover = integer("monsterBookCover").default(0)
    val summonValue = integer("summonValue").default(0)
    val petHp = integer("petHp").default(0)
    val petMp = integer("petMp").default(0)
    override val primaryKey = PrimaryKey(id)
}